services:
  server:
    build: .
    container_name: credora-server
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - credora-network
    volumes:
      - ./logs:/app/logs

networks:
  credora-network:
    driver: bridge
