version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: credora-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: credora
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - credora-network
  
  server:
    build: .
    container_name: credora-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - credora-network
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    container_name: credora-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - credora-network
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:

networks:
  credora-network:
    driver: bridge
